name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  workflow_dispatch:
    inputs:
      action:
        description: "Action to run: 'apply' (default) or 'destroy'"
        required: false
        default: "apply"

env:
  AWS_REGION: ap-south-1
  TF_VERSION: 1.13.0

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./infra
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (apply)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.action == 'apply' }}
        run: terraform plan -out=tfplan

      # - name: Terraform Plan (destroy)
      #   if: ${{ github.event_name == 'workflow_dispatch' && inputs.action == 'destroy' }}
      #   run: terraform plan -destroy -out=tfplan

      # - name: Terraform Apply (apply)
      #   if: ${{ (github.event_name != 'workflow_dispatch' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && inputs.action == 'apply') }}
      #   run: terraform apply -auto-approve tfplan

      # - name: Terraform Apply (destroy)
      #   if: ${{ github.event_name == 'workflow_dispatch' && inputs.action == 'destroy' }}
      #   run: terraform apply -auto-approve tfplan
